#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from gradelib import *

r = Runner(save("jos.out"),
           stop_breakpoint("cons_getc"))

@test(10)
def test_runner_hello():
    r.user_test("hello", timeout=30)
    r.match(r"hello, world")

@test(10)
def test_fp_context():
    r.user_test("fputest", timeout=30)
    r.match(r"^ITASK_FPTEST: OK$")

@test(10)
def test_printf_float():
    r.user_test("printfloat", timeout=30)
    r.match(r"^ITASK_PRINTF: OK$")

@test(10)
def test_printf_f():
    r.user_test("user_itask_printf_f", timeout=30)
    r.match(r"^ITASK_PRINTF_F: OK$")

@test(10)
def test_printf_width():
    r.user_test("user_itask_printf_width", timeout=30)
    r.match(r"^ITASK_PRINTF_WIDTH: OK$")

@test(10)
def test_printf_e():
    r.user_test("user_itask_printf_e", timeout=30)
    r.match(r"^ITASK_PRINTF_E: OK$")

@test(10)
def test_printf_g():
    r.user_test("user_itask_printf_g", timeout=30)
    r.match(r"^ITASK_PRINTF_G: OK$")

@test(30)
def test_musl_snprintf_fp():
    r.user_test("user_itask_musl_snprintf_fp", timeout=30)
    r.match(r"^ITASK_MUSL_SNPRINTF_FP: OK$")

run_tests()
