#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from gradelib import *

r = Runner(save("jos.out"),
           stop_breakpoint("cons_getc"))

@test(10)
def test_runner_hello():
    r.user_test("hello", timeout=30)
    r.match(r"hello, world")

@test(45)
def test_fp_context():
    r.user_test("fputest", timeout=30)
    r.match(r"^ITASK_FPTEST: OK$")

@test(45)
def test_printf_float():
    r.user_test("printfloat", timeout=30)
    r.match(r"^ITASK_PRINTF: OK$")

run_tests()
